version : "3.9"

services:
  app:
    build: .
    ports:
      - "80: 3000"
    environment:
      DATABASE_URL="postgresql://postgres:1234@localhost:5433/employeesDB?schema=public"
    depends_on:
      - DATABASE_URL

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: employeesDB
    ports:
      -"5433:5433"
    volumes:
      -postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: